### PR TITLE
Strict redis flag, closes #11

### LINKED ISSUE #11: Allow using redis.StrictRedis instead of hardcoding redis.Redis
The summary says it all.

### PR DESCRIPTION
**Pull request by grivescorbett**
Here's an implementation of this with a strict flag defaulting to False.

### CODE REVIEW

**Comment by brouberol** [comment]
Can we merge this? That'd clearly be helpful :)

**Comment by underyx** [comment]
Hey @brouberol! I just took over the repository from the original author, and will look through all outstanding pull requests in the coming few days. Expect this to be merged & released by Wednesday or so.

**Comment by brouberol** [comment]
Hi @underyx . Thanks for letting me know :smile:

**Comment by underyx** [comment]
@grivescorbett: By the time I got to your PR the code was so different that it was easier to just entirely reimplement your changes in my own commit, 1a4327cf18446a34154db648b70c3d8b1a77def7. Still, thanks a lot for your contribution!

@egeland & @brouberol: You'll be happy to see that v0.1.0 is out now, and it includes this feature, too. Have fun with it!

**Comment by brouberol** [comment]
Superb!

--
B


On Wed, Apr 15, 2015, at 01:53 AM, Bence Nagy wrote:
> @grivescorbett[1]: By the time I got to your PR the code was so
> different that it was easier to just entirely reimplement your changes
> in my own commit, 1a4327c[2]. Still, thanks a lot for your
> contribution!


> @egeland[3] & @brouberol[4]: You'll be happy to see that v0.1.0 is out
> now, and it includes this feature, too. Have fun with it!


> — Reply to this email directly or view it on GitHub[5].

>



Links:

  1. https://github.com/grivescorbett
  2. https://github.com/underyx/flask-redis/commit/1a4327cf18446a34154db648b70c3d8b1a77def7
  3. https://github.com/egeland
  4. https://github.com/brouberol
  5. https://github.com/underyx/flask-redis/pull/15#issuecomment-93117553

**Pull request closed without merging**
