### PR TITLE
Improve tasks.py

### PR DESCRIPTION
**Pull request by max-k**
* Handle context handling (invoke 0.13 support)
 * Do not run unit tests when checking for pep8 compliance
 * Do not only check test file for pep8 compliance
 * Invoke py.test using /usr/bin/env to allow it running in a virtualenv
 * Improve coverage reports to show missing statements lines

### CODE REVIEW

**Comment by underyx** [comment]
Oh dear, against all odds… I was just about to push a commit this very minute that does away with `tasks.py` entirely, in favor of simply just using `tox`. In fact, I was checking coveralls to see if I need to change anything for the tox system to work, and that's where I saw your PR.

Do you think there's any reason to use invoke over tox? I now feel like it just adds unnecessary complexity. Would you be okay with me just lifting your changes into the `tox.ini` I'm about to add now?

**Comment by max-k** [comment]
Hi, no I don't think there any reason to stay with invoke instead of tox.
On the contrary, tox seems more standard.
I made this PR to make your tests work with invoke 0.13.
Feel free to close it.
I'm currently working on my own plugin based on yours to address a specific need.
I'll look further to your future changes to see if I can give me good ideas to improve my own code.

**Comment by underyx** [comment]
@max-k great, thank you so much, and I'm really sorry to see your work just go to waste!

What are the chances of the two of us working on the same exact thing at the same hour after over a year of inactivity? Gah! :D

**Comment by sils1297** [comment]
See - use issues @underyx :P

**Pull request closed without merging**
